# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

steps:
- task : PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module PnP.PowerShell -AllowPrerelease -Scope "CurrentUser" -Verbose -AllowClobber -Force
      $username = "gnsyms@svly.onmicrosoft.com"
      $password = $(PASSWORD)
      $encpassword = convertto-securestring -String $password -AsPlainText -Force
      $cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $encpassword
      Connect-PnPOnline -Url "https://svly.sharepoint.com/sites/gnsyms" -Credentials $cred
      $web = Get-PnPWeb
      Write-Host "Site title: $($web.Title)"
  env:
    PASSWORD: $(password)