# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

steps:
- task : PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module PnP.PowerShell -AllowPrerelease -Scope "CurrentUser" -Verbose -AllowClobber -Force
      $password = "$env:PASSWORD"
      $encpassword = convertto-securestring -String $password -AsPlainText -Force
      try{
      Connect-PnPOnline -Url "https://svly.sharepoint.com/sites/gnsyms/" -ClientId 5d8e4d1b-a91d-4cba-9727-4066bcb1cd0d -CertificatePath C:\Users\91748\Desktop\PowerShell.pfx -CertificatePassword $encpassword -Tenant 'svly.onmicrosoft.com'
      $web = Get-PnPWeb
      Write-Host "Site title: $($web.Title)"
      }catch
      {
        Write-Host $_.Exception.GetType().FullName, $_.Exception.Message
      }

  env:
    PASSWORD: $(password)